name: Build & Push Multi Tier Blog-App


on:

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Run Linter
        run: |
          cd server && npm install && npx eslint . || true
          cd ../client && npm install && npx eslint . || true
      
      - name: Login in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}


# Frontend Image:
      - name: Build & Push Frontend Code
        uses: docker/build-push-actions@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            gauravbanga/blog-frontend:latest
            gauravbanga/blog-frontend:${{ github.sha }}